// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: quash_proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetKVRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value           string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TimeOutDuration int64                  `protobuf:"varint,3,opt,name=time_out_duration,json=timeOutDuration,proto3" json:"time_out_duration,omitempty"`
	InitTime        int64                  `protobuf:"varint,4,opt,name=init_time,json=initTime,proto3" json:"init_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetKVRequest) Reset() {
	*x = SetKVRequest{}
	mi := &file_quash_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKVRequest) ProtoMessage() {}

func (x *SetKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKVRequest.ProtoReflect.Descriptor instead.
func (*SetKVRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{0}
}

func (x *SetKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetKVRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetKVRequest) GetTimeOutDuration() int64 {
	if x != nil {
		return x.TimeOutDuration
	}
	return 0
}

func (x *SetKVRequest) GetInitTime() int64 {
	if x != nil {
		return x.InitTime
	}
	return 0
}

type SetKVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKVResponse) Reset() {
	*x = SetKVResponse{}
	mi := &file_quash_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKVResponse) ProtoMessage() {}

func (x *SetKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKVResponse.ProtoReflect.Descriptor instead.
func (*SetKVResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{1}
}

func (x *SetKVResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type GetKVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKVRequest) Reset() {
	*x = GetKVRequest{}
	mi := &file_quash_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVRequest) ProtoMessage() {}

func (x *GetKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVRequest.ProtoReflect.Descriptor instead.
func (*GetKVRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{2}
}

func (x *GetKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetKVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKVResponse) Reset() {
	*x = GetKVResponse{}
	mi := &file_quash_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVResponse) ProtoMessage() {}

func (x *GetKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVResponse.ProtoReflect.Descriptor instead.
func (*GetKVResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{3}
}

func (x *GetKVResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteKVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKVRequest) Reset() {
	*x = DeleteKVRequest{}
	mi := &file_quash_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKVRequest) ProtoMessage() {}

func (x *DeleteKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKVRequest.ProtoReflect.Descriptor instead.
func (*DeleteKVRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteKVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKVResponse) Reset() {
	*x = DeleteKVResponse{}
	mi := &file_quash_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKVResponse) ProtoMessage() {}

func (x *DeleteKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKVResponse.ProtoReflect.Descriptor instead.
func (*DeleteKVResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteKVResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PushIntoQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushIntoQueueRequest) Reset() {
	*x = PushIntoQueueRequest{}
	mi := &file_quash_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushIntoQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushIntoQueueRequest) ProtoMessage() {}

func (x *PushIntoQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushIntoQueueRequest.ProtoReflect.Descriptor instead.
func (*PushIntoQueueRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{6}
}

func (x *PushIntoQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *PushIntoQueueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PushIntoQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushIntoQueueResponse) Reset() {
	*x = PushIntoQueueResponse{}
	mi := &file_quash_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushIntoQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushIntoQueueResponse) ProtoMessage() {}

func (x *PushIntoQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushIntoQueueResponse.ProtoReflect.Descriptor instead.
func (*PushIntoQueueResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{7}
}

func (x *PushIntoQueueResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type PopFromQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopFromQueueRequest) Reset() {
	*x = PopFromQueueRequest{}
	mi := &file_quash_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopFromQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopFromQueueRequest) ProtoMessage() {}

func (x *PopFromQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopFromQueueRequest.ProtoReflect.Descriptor instead.
func (*PopFromQueueRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{8}
}

func (x *PopFromQueueRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

type PopFromQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopFromQueueResponse) Reset() {
	*x = PopFromQueueResponse{}
	mi := &file_quash_proto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopFromQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopFromQueueResponse) ProtoMessage() {}

func (x *PopFromQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopFromQueueResponse.ProtoReflect.Descriptor instead.
func (*PopFromQueueResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{9}
}

func (x *PopFromQueueResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type QueueListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueList     []string               `protobuf:"bytes,1,rep,name=queueList,proto3" json:"queueList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueListResponse) Reset() {
	*x = QueueListResponse{}
	mi := &file_quash_proto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueListResponse) ProtoMessage() {}

func (x *QueueListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueListResponse.ProtoReflect.Descriptor instead.
func (*QueueListResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{10}
}

func (x *QueueListResponse) GetQueueList() []string {
	if x != nil {
		return x.QueueList
	}
	return nil
}

type QueueMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueMetric   map[string]int64       `protobuf:"bytes,1,rep,name=queue_metric,json=queueMetric,proto3" json:"queue_metric,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMetricResponse) Reset() {
	*x = QueueMetricResponse{}
	mi := &file_quash_proto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMetricResponse) ProtoMessage() {}

func (x *QueueMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMetricResponse.ProtoReflect.Descriptor instead.
func (*QueueMetricResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{11}
}

func (x *QueueMetricResponse) GetQueueMetric() map[string]int64 {
	if x != nil {
		return x.QueueMetric
	}
	return nil
}

type QueryQueueListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryQueueListRequest) Reset() {
	*x = QueryQueueListRequest{}
	mi := &file_quash_proto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryQueueListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryQueueListRequest) ProtoMessage() {}

func (x *QueryQueueListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryQueueListRequest.ProtoReflect.Descriptor instead.
func (*QueryQueueListRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{12}
}

type QueryQueueMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryQueueMetricRequest) Reset() {
	*x = QueryQueueMetricRequest{}
	mi := &file_quash_proto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryQueueMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryQueueMetricRequest) ProtoMessage() {}

func (x *QueryQueueMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryQueueMetricRequest.ProtoReflect.Descriptor instead.
func (*QueryQueueMetricRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{13}
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_quash_proto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{14}
}

func (x *CreateTopicRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_quash_proto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{15}
}

func (x *CreateTopicResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type RemoveTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTopicRequest) Reset() {
	*x = RemoveTopicRequest{}
	mi := &file_quash_proto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTopicRequest) ProtoMessage() {}

func (x *RemoveTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTopicRequest.ProtoReflect.Descriptor instead.
func (*RemoveTopicRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveTopicRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type RemoveTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTopicResponse) Reset() {
	*x = RemoveTopicResponse{}
	mi := &file_quash_proto_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTopicResponse) ProtoMessage() {}

func (x *RemoveTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTopicResponse.ProtoReflect.Descriptor instead.
func (*RemoveTopicResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveTopicResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_quash_proto_proto protoreflect.FileDescriptor

const file_quash_proto_proto_rawDesc = "" +
	"\n" +
	"\x11quash_proto.proto\x12\vquash_proto\"\x7f\n" +
	"\fSetKVRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12*\n" +
	"\x11time_out_duration\x18\x03 \x01(\x03R\x0ftimeOutDuration\x12\x1b\n" +
	"\tinit_time\x18\x04 \x01(\x03R\binitTime\"+\n" +
	"\rSetKVResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\" \n" +
	"\fGetKVRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"%\n" +
	"\rGetKVResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"#\n" +
	"\x0fDeleteKVRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"(\n" +
	"\x10DeleteKVResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"K\n" +
	"\x14PushIntoQueueRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"3\n" +
	"\x15PushIntoQueueResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"4\n" +
	"\x13PopFromQueueRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\"2\n" +
	"\x14PopFromQueueResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"1\n" +
	"\x11QueueListResponse\x12\x1c\n" +
	"\tqueueList\x18\x01 \x03(\tR\tqueueList\"\xab\x01\n" +
	"\x13QueueMetricResponse\x12T\n" +
	"\fqueue_metric\x18\x01 \x03(\v21.quash_proto.QueueMetricResponse.QueueMetricEntryR\vqueueMetric\x1a>\n" +
	"\x10QueueMetricEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x17\n" +
	"\x15QueryQueueListRequest\"\x19\n" +
	"\x17QueryQueueMetricRequest\"3\n" +
	"\x12CreateTopicRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"1\n" +
	"\x13CreateTopicResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"3\n" +
	"\x12RemoveTopicRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"1\n" +
	"\x13RemoveTopicResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2\xd6\x05\n" +
	"\fQuashService\x12>\n" +
	"\x05SetKV\x12\x19.quash_proto.SetKVRequest\x1a\x1a.quash_proto.SetKVResponse\x12>\n" +
	"\x05GetKV\x12\x19.quash_proto.GetKVRequest\x1a\x1a.quash_proto.GetKVResponse\x12G\n" +
	"\bDeleteKV\x12\x1c.quash_proto.DeleteKVRequest\x1a\x1d.quash_proto.DeleteKVResponse\x12P\n" +
	"\vCreateTopic\x12\x1f.quash_proto.CreateTopicRequest\x1a .quash_proto.CreateTopicResponse\x12P\n" +
	"\vRemoveTopic\x12\x1f.quash_proto.RemoveTopicRequest\x1a .quash_proto.RemoveTopicResponse\x12R\n" +
	"\tPushQueue\x12!.quash_proto.PushIntoQueueRequest\x1a\".quash_proto.PushIntoQueueResponse\x12Q\n" +
	"\bPopQueue\x12 .quash_proto.PopFromQueueRequest\x1a!.quash_proto.PopFromQueueResponse0\x01\x12T\n" +
	"\x0eQueryQueueList\x12\".quash_proto.QueryQueueListRequest\x1a\x1e.quash_proto.QueueListResponse\x12\\\n" +
	"\x10QueryQueueMetric\x12$.quash_proto.QueryQueueMetricRequest\x1a .quash_proto.QueueMetricResponse0\x01B\"Z github.com/mddfaisal/quash/protob\x06proto3"

var (
	file_quash_proto_proto_rawDescOnce sync.Once
	file_quash_proto_proto_rawDescData []byte
)

func file_quash_proto_proto_rawDescGZIP() []byte {
	file_quash_proto_proto_rawDescOnce.Do(func() {
		file_quash_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quash_proto_proto_rawDesc), len(file_quash_proto_proto_rawDesc)))
	})
	return file_quash_proto_proto_rawDescData
}

var file_quash_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_quash_proto_proto_goTypes = []any{
	(*SetKVRequest)(nil),            // 0: quash_proto.SetKVRequest
	(*SetKVResponse)(nil),           // 1: quash_proto.SetKVResponse
	(*GetKVRequest)(nil),            // 2: quash_proto.GetKVRequest
	(*GetKVResponse)(nil),           // 3: quash_proto.GetKVResponse
	(*DeleteKVRequest)(nil),         // 4: quash_proto.DeleteKVRequest
	(*DeleteKVResponse)(nil),        // 5: quash_proto.DeleteKVResponse
	(*PushIntoQueueRequest)(nil),    // 6: quash_proto.PushIntoQueueRequest
	(*PushIntoQueueResponse)(nil),   // 7: quash_proto.PushIntoQueueResponse
	(*PopFromQueueRequest)(nil),     // 8: quash_proto.PopFromQueueRequest
	(*PopFromQueueResponse)(nil),    // 9: quash_proto.PopFromQueueResponse
	(*QueueListResponse)(nil),       // 10: quash_proto.QueueListResponse
	(*QueueMetricResponse)(nil),     // 11: quash_proto.QueueMetricResponse
	(*QueryQueueListRequest)(nil),   // 12: quash_proto.QueryQueueListRequest
	(*QueryQueueMetricRequest)(nil), // 13: quash_proto.QueryQueueMetricRequest
	(*CreateTopicRequest)(nil),      // 14: quash_proto.CreateTopicRequest
	(*CreateTopicResponse)(nil),     // 15: quash_proto.CreateTopicResponse
	(*RemoveTopicRequest)(nil),      // 16: quash_proto.RemoveTopicRequest
	(*RemoveTopicResponse)(nil),     // 17: quash_proto.RemoveTopicResponse
	nil,                             // 18: quash_proto.QueueMetricResponse.QueueMetricEntry
}
var file_quash_proto_proto_depIdxs = []int32{
	18, // 0: quash_proto.QueueMetricResponse.queue_metric:type_name -> quash_proto.QueueMetricResponse.QueueMetricEntry
	0,  // 1: quash_proto.QuashService.SetKV:input_type -> quash_proto.SetKVRequest
	2,  // 2: quash_proto.QuashService.GetKV:input_type -> quash_proto.GetKVRequest
	4,  // 3: quash_proto.QuashService.DeleteKV:input_type -> quash_proto.DeleteKVRequest
	14, // 4: quash_proto.QuashService.CreateTopic:input_type -> quash_proto.CreateTopicRequest
	16, // 5: quash_proto.QuashService.RemoveTopic:input_type -> quash_proto.RemoveTopicRequest
	6,  // 6: quash_proto.QuashService.PushQueue:input_type -> quash_proto.PushIntoQueueRequest
	8,  // 7: quash_proto.QuashService.PopQueue:input_type -> quash_proto.PopFromQueueRequest
	12, // 8: quash_proto.QuashService.QueryQueueList:input_type -> quash_proto.QueryQueueListRequest
	13, // 9: quash_proto.QuashService.QueryQueueMetric:input_type -> quash_proto.QueryQueueMetricRequest
	1,  // 10: quash_proto.QuashService.SetKV:output_type -> quash_proto.SetKVResponse
	3,  // 11: quash_proto.QuashService.GetKV:output_type -> quash_proto.GetKVResponse
	5,  // 12: quash_proto.QuashService.DeleteKV:output_type -> quash_proto.DeleteKVResponse
	15, // 13: quash_proto.QuashService.CreateTopic:output_type -> quash_proto.CreateTopicResponse
	17, // 14: quash_proto.QuashService.RemoveTopic:output_type -> quash_proto.RemoveTopicResponse
	7,  // 15: quash_proto.QuashService.PushQueue:output_type -> quash_proto.PushIntoQueueResponse
	9,  // 16: quash_proto.QuashService.PopQueue:output_type -> quash_proto.PopFromQueueResponse
	10, // 17: quash_proto.QuashService.QueryQueueList:output_type -> quash_proto.QueueListResponse
	11, // 18: quash_proto.QuashService.QueryQueueMetric:output_type -> quash_proto.QueueMetricResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_quash_proto_proto_init() }
func file_quash_proto_proto_init() {
	if File_quash_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quash_proto_proto_rawDesc), len(file_quash_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quash_proto_proto_goTypes,
		DependencyIndexes: file_quash_proto_proto_depIdxs,
		MessageInfos:      file_quash_proto_proto_msgTypes,
	}.Build()
	File_quash_proto_proto = out.File
	file_quash_proto_proto_goTypes = nil
	file_quash_proto_proto_depIdxs = nil
}
