syntax = "proto3";

package quash_proto;

option go_package = "github.com/mddfaisal/quash/proto";

message SetKVRequest {
    string key = 1;
    string value = 2;
    int64 time_out_duration = 3;
    int64 init_time = 4;
}

message SetKVResponse {
    string response = 1;
}

message GetKVRequest {
    string key = 1;
}

message GetKVResponse {
    string value = 1;
}

message DeleteKVRequest {
    string key = 1;
}

message DeleteKVResponse {
    string value = 1;
}

message PublishRequest {
    string topic_name = 1;
    string value = 2;
}

message PublishResponse {
    string response = 1; 
}

message SubscribeRequest {
    string topic_name = 1;
}

message SubscribeResponse {
    string response = 1;
}

message QueueTopicListResponse {
    repeated string topic_list = 1;
}

message QueueTopicMetricResponse {
    map<string, int64> queue_metric = 1;
}

message QueryTopicListRequest{}

message QueryTopicMetricRequest{}

message CreateTopicRequest{
    string topic_name = 1;
}

message CreateTopicResponse{
    string response = 1;
}

message RemoveTopicRequest{
    string topic_name = 1;
}

message RemoveTopicResponse{
    string response = 1;
}

message AddSubscriberRequest{
    string topic_name = 1;
}

message AddSubscriberResponse{
    string response = 1;
}

service QuashService {

    rpc SetKV (SetKVRequest) returns (SetKVResponse);
    rpc GetKV (GetKVRequest) returns (GetKVResponse);
    rpc DeleteKV (DeleteKVRequest) returns (DeleteKVResponse);

    rpc CreateTopic(CreateTopicRequest) returns (CreateTopicResponse);
    rpc RemoveTopic(RemoveTopicRequest) returns (RemoveTopicResponse);
    rpc AddSubscriber(AddSubscriberRequest) returns (stream AddSubscriberResponse);

    rpc Publish (stream PublishRequest) returns (stream PublishResponse);
    rpc Subscribe (stream SubscribeRequest) returns (stream SubscribeResponse);

    rpc QueryTopicList(QueryTopicListRequest) returns (QueueTopicListResponse);
    rpc QueryTopicMetric(QueryTopicMetricRequest) returns (stream QueueTopicMetricResponse);
}