// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: quash_proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuashService_SetKV_FullMethodName            = "/quash_proto.QuashService/SetKV"
	QuashService_GetKV_FullMethodName            = "/quash_proto.QuashService/GetKV"
	QuashService_DeleteKV_FullMethodName         = "/quash_proto.QuashService/DeleteKV"
	QuashService_CreateTopic_FullMethodName      = "/quash_proto.QuashService/CreateTopic"
	QuashService_RemoveTopic_FullMethodName      = "/quash_proto.QuashService/RemoveTopic"
	QuashService_AddSubscriber_FullMethodName    = "/quash_proto.QuashService/AddSubscriber"
	QuashService_RemoveSubscriber_FullMethodName = "/quash_proto.QuashService/RemoveSubscriber"
	QuashService_Publish_FullMethodName          = "/quash_proto.QuashService/Publish"
	QuashService_Consume_FullMethodName          = "/quash_proto.QuashService/Consume"
)

// QuashServiceClient is the client API for QuashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuashServiceClient interface {
	SetKV(ctx context.Context, in *SetKVRequest, opts ...grpc.CallOption) (*SetKVResponse, error)
	GetKV(ctx context.Context, in *GetKVRequest, opts ...grpc.CallOption) (*GetKVResponse, error)
	DeleteKV(ctx context.Context, in *DeleteKVRequest, opts ...grpc.CallOption) (*DeleteKVResponse, error)
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	RemoveTopic(ctx context.Context, in *RemoveTopicRequest, opts ...grpc.CallOption) (*RemoveTopicResponse, error)
	AddSubscriber(ctx context.Context, in *AddSubscriberRequest, opts ...grpc.CallOption) (*AddSubscriberResponse, error)
	RemoveSubscriber(ctx context.Context, in *RemoveSubscriberRequest, opts ...grpc.CallOption) (*RemoveSubscriberResponse, error)
	Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error)
	Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeRequest, ConsumeResponse], error)
}

type quashServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuashServiceClient(cc grpc.ClientConnInterface) QuashServiceClient {
	return &quashServiceClient{cc}
}

func (c *quashServiceClient) SetKV(ctx context.Context, in *SetKVRequest, opts ...grpc.CallOption) (*SetKVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetKVResponse)
	err := c.cc.Invoke(ctx, QuashService_SetKV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quashServiceClient) GetKV(ctx context.Context, in *GetKVRequest, opts ...grpc.CallOption) (*GetKVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKVResponse)
	err := c.cc.Invoke(ctx, QuashService_GetKV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quashServiceClient) DeleteKV(ctx context.Context, in *DeleteKVRequest, opts ...grpc.CallOption) (*DeleteKVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKVResponse)
	err := c.cc.Invoke(ctx, QuashService_DeleteKV_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quashServiceClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, QuashService_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quashServiceClient) RemoveTopic(ctx context.Context, in *RemoveTopicRequest, opts ...grpc.CallOption) (*RemoveTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTopicResponse)
	err := c.cc.Invoke(ctx, QuashService_RemoveTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quashServiceClient) AddSubscriber(ctx context.Context, in *AddSubscriberRequest, opts ...grpc.CallOption) (*AddSubscriberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSubscriberResponse)
	err := c.cc.Invoke(ctx, QuashService_AddSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quashServiceClient) RemoveSubscriber(ctx context.Context, in *RemoveSubscriberRequest, opts ...grpc.CallOption) (*RemoveSubscriberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSubscriberResponse)
	err := c.cc.Invoke(ctx, QuashService_RemoveSubscriber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quashServiceClient) Publish(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PublishRequest, PublishResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuashService_ServiceDesc.Streams[0], QuashService_Publish_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PublishRequest, PublishResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuashService_PublishClient = grpc.BidiStreamingClient[PublishRequest, PublishResponse]

func (c *quashServiceClient) Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeRequest, ConsumeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QuashService_ServiceDesc.Streams[1], QuashService_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeRequest, ConsumeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuashService_ConsumeClient = grpc.BidiStreamingClient[ConsumeRequest, ConsumeResponse]

// QuashServiceServer is the server API for QuashService service.
// All implementations must embed UnimplementedQuashServiceServer
// for forward compatibility.
type QuashServiceServer interface {
	SetKV(context.Context, *SetKVRequest) (*SetKVResponse, error)
	GetKV(context.Context, *GetKVRequest) (*GetKVResponse, error)
	DeleteKV(context.Context, *DeleteKVRequest) (*DeleteKVResponse, error)
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	RemoveTopic(context.Context, *RemoveTopicRequest) (*RemoveTopicResponse, error)
	AddSubscriber(context.Context, *AddSubscriberRequest) (*AddSubscriberResponse, error)
	RemoveSubscriber(context.Context, *RemoveSubscriberRequest) (*RemoveSubscriberResponse, error)
	Publish(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error
	Consume(grpc.BidiStreamingServer[ConsumeRequest, ConsumeResponse]) error
	mustEmbedUnimplementedQuashServiceServer()
}

// UnimplementedQuashServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuashServiceServer struct{}

func (UnimplementedQuashServiceServer) SetKV(context.Context, *SetKVRequest) (*SetKVResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetKV not implemented")
}
func (UnimplementedQuashServiceServer) GetKV(context.Context, *GetKVRequest) (*GetKVResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKV not implemented")
}
func (UnimplementedQuashServiceServer) DeleteKV(context.Context, *DeleteKVRequest) (*DeleteKVResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKV not implemented")
}
func (UnimplementedQuashServiceServer) CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedQuashServiceServer) RemoveTopic(context.Context, *RemoveTopicRequest) (*RemoveTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTopic not implemented")
}
func (UnimplementedQuashServiceServer) AddSubscriber(context.Context, *AddSubscriberRequest) (*AddSubscriberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSubscriber not implemented")
}
func (UnimplementedQuashServiceServer) RemoveSubscriber(context.Context, *RemoveSubscriberRequest) (*RemoveSubscriberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSubscriber not implemented")
}
func (UnimplementedQuashServiceServer) Publish(grpc.BidiStreamingServer[PublishRequest, PublishResponse]) error {
	return status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedQuashServiceServer) Consume(grpc.BidiStreamingServer[ConsumeRequest, ConsumeResponse]) error {
	return status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedQuashServiceServer) mustEmbedUnimplementedQuashServiceServer() {}
func (UnimplementedQuashServiceServer) testEmbeddedByValue()                      {}

// UnsafeQuashServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuashServiceServer will
// result in compilation errors.
type UnsafeQuashServiceServer interface {
	mustEmbedUnimplementedQuashServiceServer()
}

func RegisterQuashServiceServer(s grpc.ServiceRegistrar, srv QuashServiceServer) {
	// If the following call panics, it indicates UnimplementedQuashServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuashService_ServiceDesc, srv)
}

func _QuashService_SetKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuashServiceServer).SetKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuashService_SetKV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuashServiceServer).SetKV(ctx, req.(*SetKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuashService_GetKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuashServiceServer).GetKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuashService_GetKV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuashServiceServer).GetKV(ctx, req.(*GetKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuashService_DeleteKV_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKVRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuashServiceServer).DeleteKV(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuashService_DeleteKV_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuashServiceServer).DeleteKV(ctx, req.(*DeleteKVRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuashService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuashServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuashService_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuashServiceServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuashService_RemoveTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuashServiceServer).RemoveTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuashService_RemoveTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuashServiceServer).RemoveTopic(ctx, req.(*RemoveTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuashService_AddSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuashServiceServer).AddSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuashService_AddSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuashServiceServer).AddSubscriber(ctx, req.(*AddSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuashService_RemoveSubscriber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSubscriberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuashServiceServer).RemoveSubscriber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuashService_RemoveSubscriber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuashServiceServer).RemoveSubscriber(ctx, req.(*RemoveSubscriberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuashService_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(QuashServiceServer).Publish(&grpc.GenericServerStream[PublishRequest, PublishResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuashService_PublishServer = grpc.BidiStreamingServer[PublishRequest, PublishResponse]

func _QuashService_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(QuashServiceServer).Consume(&grpc.GenericServerStream[ConsumeRequest, ConsumeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QuashService_ConsumeServer = grpc.BidiStreamingServer[ConsumeRequest, ConsumeResponse]

// QuashService_ServiceDesc is the grpc.ServiceDesc for QuashService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuashService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quash_proto.QuashService",
	HandlerType: (*QuashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetKV",
			Handler:    _QuashService_SetKV_Handler,
		},
		{
			MethodName: "GetKV",
			Handler:    _QuashService_GetKV_Handler,
		},
		{
			MethodName: "DeleteKV",
			Handler:    _QuashService_DeleteKV_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _QuashService_CreateTopic_Handler,
		},
		{
			MethodName: "RemoveTopic",
			Handler:    _QuashService_RemoveTopic_Handler,
		},
		{
			MethodName: "AddSubscriber",
			Handler:    _QuashService_AddSubscriber_Handler,
		},
		{
			MethodName: "RemoveSubscriber",
			Handler:    _QuashService_RemoveSubscriber_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _QuashService_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Consume",
			Handler:       _QuashService_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "quash_proto.proto",
}
