// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: quash_proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetKVRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value           string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TimeOutDuration int64                  `protobuf:"varint,3,opt,name=time_out_duration,json=timeOutDuration,proto3" json:"time_out_duration,omitempty"`
	InitTime        int64                  `protobuf:"varint,4,opt,name=init_time,json=initTime,proto3" json:"init_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetKVRequest) Reset() {
	*x = SetKVRequest{}
	mi := &file_quash_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKVRequest) ProtoMessage() {}

func (x *SetKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKVRequest.ProtoReflect.Descriptor instead.
func (*SetKVRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{0}
}

func (x *SetKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetKVRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetKVRequest) GetTimeOutDuration() int64 {
	if x != nil {
		return x.TimeOutDuration
	}
	return 0
}

func (x *SetKVRequest) GetInitTime() int64 {
	if x != nil {
		return x.InitTime
	}
	return 0
}

type SetKVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKVResponse) Reset() {
	*x = SetKVResponse{}
	mi := &file_quash_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKVResponse) ProtoMessage() {}

func (x *SetKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKVResponse.ProtoReflect.Descriptor instead.
func (*SetKVResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{1}
}

func (x *SetKVResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type GetKVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKVRequest) Reset() {
	*x = GetKVRequest{}
	mi := &file_quash_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVRequest) ProtoMessage() {}

func (x *GetKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVRequest.ProtoReflect.Descriptor instead.
func (*GetKVRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{2}
}

func (x *GetKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetKVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKVResponse) Reset() {
	*x = GetKVResponse{}
	mi := &file_quash_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKVResponse) ProtoMessage() {}

func (x *GetKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKVResponse.ProtoReflect.Descriptor instead.
func (*GetKVResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{3}
}

func (x *GetKVResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteKVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKVRequest) Reset() {
	*x = DeleteKVRequest{}
	mi := &file_quash_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKVRequest) ProtoMessage() {}

func (x *DeleteKVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKVRequest.ProtoReflect.Descriptor instead.
func (*DeleteKVRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteKVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKVResponse) Reset() {
	*x = DeleteKVResponse{}
	mi := &file_quash_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKVResponse) ProtoMessage() {}

func (x *DeleteKVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKVResponse.ProtoReflect.Descriptor instead.
func (*DeleteKVResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteKVResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_quash_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{6}
}

func (x *PublishRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *PublishRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_quash_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{7}
}

func (x *PublishResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	SubscriberId  string                 `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_quash_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{8}
}

func (x *ConsumeRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *ConsumeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_quash_proto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumeResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type QueueTopicListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicList     []string               `protobuf:"bytes,1,rep,name=topic_list,json=topicList,proto3" json:"topic_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueTopicListResponse) Reset() {
	*x = QueueTopicListResponse{}
	mi := &file_quash_proto_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueTopicListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueTopicListResponse) ProtoMessage() {}

func (x *QueueTopicListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueTopicListResponse.ProtoReflect.Descriptor instead.
func (*QueueTopicListResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{10}
}

func (x *QueueTopicListResponse) GetTopicList() []string {
	if x != nil {
		return x.TopicList
	}
	return nil
}

type QueueMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueMetric   map[string]int64       `protobuf:"bytes,1,rep,name=queue_metric,json=queueMetric,proto3" json:"queue_metric,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMetric) Reset() {
	*x = QueueMetric{}
	mi := &file_quash_proto_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMetric) ProtoMessage() {}

func (x *QueueMetric) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMetric.ProtoReflect.Descriptor instead.
func (*QueueMetric) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{11}
}

func (x *QueueMetric) GetQueueMetric() map[string]int64 {
	if x != nil {
		return x.QueueMetric
	}
	return nil
}

type QueueTopicMetricResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	QueueMetric   map[string]*QueueMetric `protobuf:"bytes,1,rep,name=queue_metric,json=queueMetric,proto3" json:"queue_metric,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueTopicMetricResponse) Reset() {
	*x = QueueTopicMetricResponse{}
	mi := &file_quash_proto_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueTopicMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueTopicMetricResponse) ProtoMessage() {}

func (x *QueueTopicMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueTopicMetricResponse.ProtoReflect.Descriptor instead.
func (*QueueTopicMetricResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{12}
}

func (x *QueueTopicMetricResponse) GetQueueMetric() map[string]*QueueMetric {
	if x != nil {
		return x.QueueMetric
	}
	return nil
}

type QueryTopicListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTopicListRequest) Reset() {
	*x = QueryTopicListRequest{}
	mi := &file_quash_proto_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTopicListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTopicListRequest) ProtoMessage() {}

func (x *QueryTopicListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTopicListRequest.ProtoReflect.Descriptor instead.
func (*QueryTopicListRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{13}
}

type QueryTopicMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTopicMetricRequest) Reset() {
	*x = QueryTopicMetricRequest{}
	mi := &file_quash_proto_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTopicMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTopicMetricRequest) ProtoMessage() {}

func (x *QueryTopicMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTopicMetricRequest.ProtoReflect.Descriptor instead.
func (*QueryTopicMetricRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{14}
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_quash_proto_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{15}
}

func (x *CreateTopicRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_quash_proto_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{16}
}

func (x *CreateTopicResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type RemoveTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTopicRequest) Reset() {
	*x = RemoveTopicRequest{}
	mi := &file_quash_proto_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTopicRequest) ProtoMessage() {}

func (x *RemoveTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTopicRequest.ProtoReflect.Descriptor instead.
func (*RemoveTopicRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveTopicRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type RemoveTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTopicResponse) Reset() {
	*x = RemoveTopicResponse{}
	mi := &file_quash_proto_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTopicResponse) ProtoMessage() {}

func (x *RemoveTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTopicResponse.ProtoReflect.Descriptor instead.
func (*RemoveTopicResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveTopicResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type AddSubscriberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriberRequest) Reset() {
	*x = AddSubscriberRequest{}
	mi := &file_quash_proto_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriberRequest) ProtoMessage() {}

func (x *AddSubscriberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriberRequest.ProtoReflect.Descriptor instead.
func (*AddSubscriberRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{19}
}

func (x *AddSubscriberRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type AddSubscriberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	SubscriberId  string                 `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriberResponse) Reset() {
	*x = AddSubscriberResponse{}
	mi := &file_quash_proto_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriberResponse) ProtoMessage() {}

func (x *AddSubscriberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriberResponse.ProtoReflect.Descriptor instead.
func (*AddSubscriberResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{20}
}

func (x *AddSubscriberResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *AddSubscriberResponse) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

type RemoveSubscriberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicName     string                 `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	SubscriberId  string                 `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriberRequest) Reset() {
	*x = RemoveSubscriberRequest{}
	mi := &file_quash_proto_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriberRequest) ProtoMessage() {}

func (x *RemoveSubscriberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriberRequest.ProtoReflect.Descriptor instead.
func (*RemoveSubscriberRequest) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveSubscriberRequest) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *RemoveSubscriberRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

type RemoveSubscriberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSubscriberResponse) Reset() {
	*x = RemoveSubscriberResponse{}
	mi := &file_quash_proto_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSubscriberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSubscriberResponse) ProtoMessage() {}

func (x *RemoveSubscriberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quash_proto_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSubscriberResponse.ProtoReflect.Descriptor instead.
func (*RemoveSubscriberResponse) Descriptor() ([]byte, []int) {
	return file_quash_proto_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveSubscriberResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_quash_proto_proto protoreflect.FileDescriptor

const file_quash_proto_proto_rawDesc = "" +
	"\n" +
	"\x11quash_proto.proto\x12\vquash_proto\"\x7f\n" +
	"\fSetKVRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12*\n" +
	"\x11time_out_duration\x18\x03 \x01(\x03R\x0ftimeOutDuration\x12\x1b\n" +
	"\tinit_time\x18\x04 \x01(\x03R\binitTime\"+\n" +
	"\rSetKVResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\" \n" +
	"\fGetKVRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"%\n" +
	"\rGetKVResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"#\n" +
	"\x0fDeleteKVRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"(\n" +
	"\x10DeleteKVResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"E\n" +
	"\x0ePublishRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"-\n" +
	"\x0fPublishResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"T\n" +
	"\x0eConsumeRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\tR\fsubscriberId\"-\n" +
	"\x0fConsumeResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"7\n" +
	"\x16QueueTopicListResponse\x12\x1d\n" +
	"\n" +
	"topic_list\x18\x01 \x03(\tR\ttopicList\"\x9b\x01\n" +
	"\vQueueMetric\x12L\n" +
	"\fqueue_metric\x18\x01 \x03(\v2).quash_proto.QueueMetric.QueueMetricEntryR\vqueueMetric\x1a>\n" +
	"\x10QueueMetricEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xcf\x01\n" +
	"\x18QueueTopicMetricResponse\x12Y\n" +
	"\fqueue_metric\x18\x01 \x03(\v26.quash_proto.QueueTopicMetricResponse.QueueMetricEntryR\vqueueMetric\x1aX\n" +
	"\x10QueueMetricEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.quash_proto.QueueMetricR\x05value:\x028\x01\"\x17\n" +
	"\x15QueryTopicListRequest\"\x19\n" +
	"\x17QueryTopicMetricRequest\"3\n" +
	"\x12CreateTopicRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"1\n" +
	"\x13CreateTopicResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"3\n" +
	"\x12RemoveTopicRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"1\n" +
	"\x13RemoveTopicResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\"5\n" +
	"\x14AddSubscriberRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\"X\n" +
	"\x15AddSubscriberResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\tR\fsubscriberId\"]\n" +
	"\x17RemoveSubscriberRequest\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x01 \x01(\tR\ttopicName\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\tR\fsubscriberId\"6\n" +
	"\x18RemoveSubscriberResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2\xc8\x05\n" +
	"\fQuashService\x12>\n" +
	"\x05SetKV\x12\x19.quash_proto.SetKVRequest\x1a\x1a.quash_proto.SetKVResponse\x12>\n" +
	"\x05GetKV\x12\x19.quash_proto.GetKVRequest\x1a\x1a.quash_proto.GetKVResponse\x12G\n" +
	"\bDeleteKV\x12\x1c.quash_proto.DeleteKVRequest\x1a\x1d.quash_proto.DeleteKVResponse\x12P\n" +
	"\vCreateTopic\x12\x1f.quash_proto.CreateTopicRequest\x1a .quash_proto.CreateTopicResponse\x12P\n" +
	"\vRemoveTopic\x12\x1f.quash_proto.RemoveTopicRequest\x1a .quash_proto.RemoveTopicResponse\x12V\n" +
	"\rAddSubscriber\x12!.quash_proto.AddSubscriberRequest\x1a\".quash_proto.AddSubscriberResponse\x12_\n" +
	"\x10RemoveSubscriber\x12$.quash_proto.RemoveSubscriberRequest\x1a%.quash_proto.RemoveSubscriberResponse\x12H\n" +
	"\aPublish\x12\x1b.quash_proto.PublishRequest\x1a\x1c.quash_proto.PublishResponse(\x010\x01\x12H\n" +
	"\aConsume\x12\x1b.quash_proto.ConsumeRequest\x1a\x1c.quash_proto.ConsumeResponse(\x010\x01B\"Z github.com/mddfaisal/quash/protob\x06proto3"

var (
	file_quash_proto_proto_rawDescOnce sync.Once
	file_quash_proto_proto_rawDescData []byte
)

func file_quash_proto_proto_rawDescGZIP() []byte {
	file_quash_proto_proto_rawDescOnce.Do(func() {
		file_quash_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quash_proto_proto_rawDesc), len(file_quash_proto_proto_rawDesc)))
	})
	return file_quash_proto_proto_rawDescData
}

var file_quash_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_quash_proto_proto_goTypes = []any{
	(*SetKVRequest)(nil),             // 0: quash_proto.SetKVRequest
	(*SetKVResponse)(nil),            // 1: quash_proto.SetKVResponse
	(*GetKVRequest)(nil),             // 2: quash_proto.GetKVRequest
	(*GetKVResponse)(nil),            // 3: quash_proto.GetKVResponse
	(*DeleteKVRequest)(nil),          // 4: quash_proto.DeleteKVRequest
	(*DeleteKVResponse)(nil),         // 5: quash_proto.DeleteKVResponse
	(*PublishRequest)(nil),           // 6: quash_proto.PublishRequest
	(*PublishResponse)(nil),          // 7: quash_proto.PublishResponse
	(*ConsumeRequest)(nil),           // 8: quash_proto.ConsumeRequest
	(*ConsumeResponse)(nil),          // 9: quash_proto.ConsumeResponse
	(*QueueTopicListResponse)(nil),   // 10: quash_proto.QueueTopicListResponse
	(*QueueMetric)(nil),              // 11: quash_proto.QueueMetric
	(*QueueTopicMetricResponse)(nil), // 12: quash_proto.QueueTopicMetricResponse
	(*QueryTopicListRequest)(nil),    // 13: quash_proto.QueryTopicListRequest
	(*QueryTopicMetricRequest)(nil),  // 14: quash_proto.QueryTopicMetricRequest
	(*CreateTopicRequest)(nil),       // 15: quash_proto.CreateTopicRequest
	(*CreateTopicResponse)(nil),      // 16: quash_proto.CreateTopicResponse
	(*RemoveTopicRequest)(nil),       // 17: quash_proto.RemoveTopicRequest
	(*RemoveTopicResponse)(nil),      // 18: quash_proto.RemoveTopicResponse
	(*AddSubscriberRequest)(nil),     // 19: quash_proto.AddSubscriberRequest
	(*AddSubscriberResponse)(nil),    // 20: quash_proto.AddSubscriberResponse
	(*RemoveSubscriberRequest)(nil),  // 21: quash_proto.RemoveSubscriberRequest
	(*RemoveSubscriberResponse)(nil), // 22: quash_proto.RemoveSubscriberResponse
	nil,                              // 23: quash_proto.QueueMetric.QueueMetricEntry
	nil,                              // 24: quash_proto.QueueTopicMetricResponse.QueueMetricEntry
}
var file_quash_proto_proto_depIdxs = []int32{
	23, // 0: quash_proto.QueueMetric.queue_metric:type_name -> quash_proto.QueueMetric.QueueMetricEntry
	24, // 1: quash_proto.QueueTopicMetricResponse.queue_metric:type_name -> quash_proto.QueueTopicMetricResponse.QueueMetricEntry
	11, // 2: quash_proto.QueueTopicMetricResponse.QueueMetricEntry.value:type_name -> quash_proto.QueueMetric
	0,  // 3: quash_proto.QuashService.SetKV:input_type -> quash_proto.SetKVRequest
	2,  // 4: quash_proto.QuashService.GetKV:input_type -> quash_proto.GetKVRequest
	4,  // 5: quash_proto.QuashService.DeleteKV:input_type -> quash_proto.DeleteKVRequest
	15, // 6: quash_proto.QuashService.CreateTopic:input_type -> quash_proto.CreateTopicRequest
	17, // 7: quash_proto.QuashService.RemoveTopic:input_type -> quash_proto.RemoveTopicRequest
	19, // 8: quash_proto.QuashService.AddSubscriber:input_type -> quash_proto.AddSubscriberRequest
	21, // 9: quash_proto.QuashService.RemoveSubscriber:input_type -> quash_proto.RemoveSubscriberRequest
	6,  // 10: quash_proto.QuashService.Publish:input_type -> quash_proto.PublishRequest
	8,  // 11: quash_proto.QuashService.Consume:input_type -> quash_proto.ConsumeRequest
	1,  // 12: quash_proto.QuashService.SetKV:output_type -> quash_proto.SetKVResponse
	3,  // 13: quash_proto.QuashService.GetKV:output_type -> quash_proto.GetKVResponse
	5,  // 14: quash_proto.QuashService.DeleteKV:output_type -> quash_proto.DeleteKVResponse
	16, // 15: quash_proto.QuashService.CreateTopic:output_type -> quash_proto.CreateTopicResponse
	18, // 16: quash_proto.QuashService.RemoveTopic:output_type -> quash_proto.RemoveTopicResponse
	20, // 17: quash_proto.QuashService.AddSubscriber:output_type -> quash_proto.AddSubscriberResponse
	22, // 18: quash_proto.QuashService.RemoveSubscriber:output_type -> quash_proto.RemoveSubscriberResponse
	7,  // 19: quash_proto.QuashService.Publish:output_type -> quash_proto.PublishResponse
	9,  // 20: quash_proto.QuashService.Consume:output_type -> quash_proto.ConsumeResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_quash_proto_proto_init() }
func file_quash_proto_proto_init() {
	if File_quash_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quash_proto_proto_rawDesc), len(file_quash_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quash_proto_proto_goTypes,
		DependencyIndexes: file_quash_proto_proto_depIdxs,
		MessageInfos:      file_quash_proto_proto_msgTypes,
	}.Build()
	File_quash_proto_proto = out.File
	file_quash_proto_proto_goTypes = nil
	file_quash_proto_proto_depIdxs = nil
}
